apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
