apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      app: hightech-vote
  template:
    metadata:
      labels:
        app: hightech-vote
    spec:
      containers:
      - name: vote
        image: '5d20240/ht-vote'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  selector:
    app: hightech-vote
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

