all:
  hosts:
    k8s1:
      ansible_host: 172.30.1.21
      ip: 172.30.1.21
      access_ip: 172.30.1.21
    k8s2:
      ansible_host: 172.30.1.22
      ip: 172.30.1.22
      access_ip: 172.30.1.22
    k8s3:
      ansible_host: 172.30.1.23
      ip: 172.30.1.23
      access_ip: 172.30.1.23
  children:
    kube_control_plane:
      hosts:
        k8s1:
        k8s2:
    kube_node:
      hosts:
        k8s1:
        k8s2:
        k8s3:
    etcd:
      hosts:
        k8s1:
        k8s2:
        k8s3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
