- name: Our vote app
  hosts: voteapp
  tasks:
    - name: Create docker bridge
      docker_network:
        name: backend
    
    - name: Start Redis
      docker_container:
        name: redis
        image: redis
        restart_policy: always
        state: started
        networks:
          - name: backend
        purge_networks: yes
        volumes:
          - /opt/redis:/data
    
    - name: Start Postgres
      docker_container:
        name: db
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        restart_policy: always
        state: started
        networks:
          - name: backend
        purge_networks: yes
        volumes:
          - /opt/pgdata:/var/lib/postgresql/data
    
    - name: Start Vote service
      docker_container:
        name: vote
        image: "5d20240/ht-vote"
        restart_policy: always
        state: started
        networks:
          - name: backend
        purge_networks: yes
        ports:
          - 3000:80
    
    - name: Start Worker service
      docker_container:
        name: worker
        image: "5d20240/ht-worker"
        restart_policy: always
        state: started
        networks:
          - name: backend
        purge_networks: yes
    
    - name: Start Result service
      docker_container:
        name: result
        image: "5d20240/ht-result"
        restart_policy: always
        state: started
        networks:
          - name: backend
        purge_networks: yes
        ports:
          - 4000:80