- name: Test
  hosts: centos
  tasks:
    - name: Enable EPEL
      dnf:
        name: epel-release
        state: present
    - name: Install common packages
      dnf:
        name:
          - vim
          - htop
          - mc
        state: present