- name: Our Voting app
  hosts: centos
  tasks:
    - name: Enable EPEL
      dnf:
        name: epel-release
        state: present
    - name: Install common packages
      dnf:
        name:
          - vim
          - htop
          - mc
        state: present
    - name: Get docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo




