apiVersion: v1
clusters:
- cluster:
    certificate-authority: /mnt/c/Users/dmitry/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 29 Sep 2021 10:20:34 MSK
        provider: minikube.sigs.k8s.io
        version: v1.23.2
      name: cluster_info
    server: https://127.0.0.1:54869
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 29 Sep 2021 10:20:34 MSK
        provider: minikube.sigs.k8s.io
        version: v1.23.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /mnt/c/Users/dmitry/.minikube/profiles/minikube/client.crt
    client-key: /mnt/c/Users/dmitry/.minikube/profiles/minikube/client.key
