apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    name: mynginx
spec:
  containers:
  - name: mynginx
    image: nginx:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
    ports:
      - containerPort: 80
    volumeMounts:
      - name:  nginx
        mountPath:  /etc/nginx/nginx.conf
        subPath: nginx.conf
  volumes:
    - name: nginx
      configMap:
        name: nginxconf
        items:
          - key: nginx.conf
            path: nginx.conf
